Fix crash when opening video on iOS 18
Fixes #13.

On iOS 18, opening a recorded video crashes with the following error:

IsItSnappy/MarkViewController.swift:28:
Fatal error: 'try!' expression unexpectedly raised an error:
Error Domain=AVFoundationErrorDomain Code=-11884
"Cannot Access URL"
UserInfo={
    NSLocalizedFailureReason=The sandbox extension was not issued.,
    NSLocalizedDescription=Cannot Access URL,
    NSUnderlyingError=0x3002b1980 {
        Error Domain=NSOSStatusErrorDomain Code=-17507 "(null)"
    }
}

This is caused by the logic in PlayerInfo.getInnerAsset to bypass the
composition's frame rate ramp by creating an AVURLAsset if we get an
AVComposition.

We can avoid this altogether by requesting the original video without
slo-mo effects from PHImageManager.